# Generated by Django 5.1.1 on 2024-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_PREPARACION', 'En preparación'), ('PREPARADO', 'Preparado')], default='EN_ESPERA', max_length=15)),
            ],
        ),
    ]
